### ISSUE TITLE
the simple example in the README, I get the error

### ISSUE THREAD

**Issue by indenkun** [XiaoruiZhu/SurrogateRsq#2]
Thank you for this very interesting package.

Whenever I run the simple example in the README to see how it behaves, I get the following error at the following point:

```r
# surrogate R-squared rank table

Rank_table_white <- 
  surr_rsq_rank(object  = select_model_white, 
                data    = WhiteWine,
                avg.num = 30)

   ## Error in if (model$method == full_model$method) { : 
   ##  argument is of length zero
```

This seems to be happening because there is no `full_model` in `select_model_white`, but isn't this example correctly as follows?

```r
# surrogate R-squared rank table

Rank_table_white <- 
  surr_rsq_rank(object  = surr_obj_white, 
                data    = WhiteWine,
                avg.num = 30)
```

Sorry if I'm wrong.
Please consider it.

**Comment by XiaoruiZhu** [comment]
Hi, 
thank you so much for checking the examples. 
Yes, you're right, the input object of surr_rsq_rank() should be a surrogate Rsq object, so it should be "surr_obj_white" as shown in yours. 

PS. we changed the input object of the rank function to be the surrogate Rsq object. The example was written very early when we design the function. Back at that time, we thought the model object could be good enough.

**Comment by XiaoruiZhu** [comment]
@indenkun Please share your comments or issues when you're using this package. We will hear and try to improve it.

**Comment by indenkun** [comment]
@XiaoruiZhu

Thank you for your reply and correction.
It is a very interesting package (calculation method) and I am following its behavior little by little. I may ask again because I don't understand a lot of things.

By the way, since you reopened it, I have to ask about the `surr_rsq()` function.
In the function description, the argument of `full_model` is "A full model that contains all of the predictors in the data set." .
However, is it not necessary for this to be a full model in terms of behavior?
Looking at the code, I think that if all the independent variables included in the model given in the `model` argument are included, the calculation result will be the same even if the model is not a full model. I am sorry if I am wrong.

So, the next part of Simple example is incorrect, if the function is as described:

```r
# surrogate R-squared
surr_obj_white <- 
  surr_rsq(model      = select_model_white,
           full_model = select_model_white, 
           data       = WhiteWine, 
           avg.num    = 30)
```

I think this is where, if the function is as described, it should correctly look like this:

```r
surr_obj_white <- 
  surr_rsq(model      = select_model_white,
           full_model = naive_model_white, 
           data       = WhiteWine, 
           avg.num    = 30)
```

However, am I wrong in assuming that the calculation results remain the same regardless of whether the above is correct or incorrect?

**Comment by XiaoruiZhu** [comment]
@indenkun 
The procedure of the surrogate R-squared is a little complicated. Theoretically, to maintain comparability, the surrogate residuals need to be generated from a full model that is large and contains most of the possible terms (possible predictors, higher-order terms, and interaction terms). In practice, we suggest investigating the linear model through variable screening/selection, and diagnostics to find that "full model" as illustrated in the flow chart. To be honest, a wrong/very off full model will affect the calculation of surrogate R-squared (the results will be different if different full models are used). 

To your second point, we believe some variables are non-signal or irrelevant predictors so the initialized full model is the selected model. With that model, we calculate the surrogate R-squared. This method needs to be implemented in that way. You may find the results could be similar if you change the full model to naive_model_white.  But it is because the extra variables in the naive_model_white are some irrelevant predictors. If the full model specified in the surr_rsq does not include an important/relevant predictor, the surrogate R-squared will be wrong. 

For details, you can refer to our two papers: 
1. https://bpspsychub.onlinelibrary.wiley.com/doi/full/10.1111/bmsp.12289
2. The second paper is the Vignettee of the CRAN page: https://cloud.r-project.org/web/packages/SurrogateRsq/index.html (This paper is still under review).  

Thanks for your review and comments.
